# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=jdvbWzcOHJAqQDFzyOgWjPXHOhisaeEb
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Stripe
stripe.api.key=sk_test_51TeSvA24kLJl6IbQqmQRA0A7sHrnKa18Iozk2VFvSG9omvLKK92WfJH4PmE55fNykcEXaiPJBaDG46X9X8WDtEl400U4nlN1Jt
stripe.webhook.secret=whsec_temp