spring.application.name=demo.payment

server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_DB
spring.datasource.username=postgres
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
stripe.api.key=sk_test_51TeSvA24kLJl6IbQqmQRA0A7sHrnKa18Iozk2VFvSG9omvLKK92WfJH4PmE55fNykcEXaiPJBaDG46X9X8WDtEl400U4nlN1Jt
stripe.currency=INR
stripe.webhook.secret=whsec_89449a5f83fd5242580ca46bfdc550da0a25ea7db918db2ee0bc2cbb650c95bf